# Generated by Django 5.2.13 on 2026-04-30 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('dci', models.CharField(help_text='Dénomination Commune Internationale', max_length=200)),
                ('forme', models.CharField(help_text='comprimé, sirop, injection...', max_length=50)),
                ('dosage', models.CharField(help_text='ex: 500mg, 250mg/5ml', max_length=50)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actuel', models.IntegerField(default=0)),
                ('stock_minimum', models.IntegerField(default=0)),
                ('date_expiration', models.DateField()),
                ('ordonnance_requise', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicaments', to='categories.categorie')),
            ],
            options={
                'ordering': ['nom'],
                'constraints': [models.CheckConstraint(condition=models.Q(('prix_achat__gte', 0)), name='prix_achat_positif'), models.CheckConstraint(condition=models.Q(('prix_vente__gte', 0)), name='prix_vente_positif'), models.CheckConstraint(condition=models.Q(('stock_actuel__gte', 0)), name='stock_actuel_positif'), models.CheckConstraint(condition=models.Q(('stock_minimum__gte', 0)), name='stock_minimum_positif')],
            },
        ),
    ]
