# Generated by Django 5.2.13 on 2026-04-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='dci',
            field=models.CharField(blank=True, help_text='Dénomination Commune Internationale', max_length=200),
        ),
    ]
